kind: Deployment
apiVersion: apps/v1
metadata:
    name: kubeserve
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: kubeserve
    template:
        metadata:
            labels:
                app: kubeserve
        spec:
            containers:
                - image: leaddevops/kubeserve:v2
                  name: app
---
kind: Service
apiVersion: v1
metadata:
    name: kubeserve-svc
spec:
    type: NodePort
    selector:
        app: kubeserve
    ports:
        - port: 80
          targetPort: 80

            
