kind: PersistentVolume
apiVersion: v1
metadata:
    name: nfs-persistentvolume
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        path: /mnt/sharedfolder
        server: 10.160.0.2 #private ip of nfs server
        readOnly: false
