kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: nfs-persistentvolumeclaim
spec:
    volumeName: nfs-persistentvolume
    resources:
        requests:
           storage: 1Gi
    accessModes:
        - ReadWriteMany
